### ISSUE TITLE
can't find pynq z1 boards files

### ISSUE THREAD

**Issue by supercooledith** [Buck008/FPGA-Based-Weight-Fixed-Systolic-Array-Matrix-Multiplier#1]
hi dear author，can't find pynq z1 boards files in https://github.com/Digilent/vivado-boards/tree/master，can you upload that？thaks！！！

**Comment by Buck008** [comment]
https://pynq.readthedocs.io/en/v3.0.0/overlay_design_methodology/board_settings.html
看看这个


***@***.***
 
From: 梁爽
Date: 2024-02-25 09:10
To: Buck008/Transformer-Accelerator-Based-on-FPGA
CC: Subscribed
Subject: [Buck008/Transformer-Accelerator-Based-on-FPGA] can't find pynq z1 boards files (Issue #1)
hi dear author，can't find pynq z1 boards files in https://github.com/Digilent/vivado-boards/tree/master，can you upload that？thaks！！！

**Comment by supercooledith** [comment]
thaks soooomuch！！！wish you good luck！！🌹
